config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
 
  # devise_for :users
  
  devise_for :users , controllers:{
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root controller: :homes , action: :index , as: :home
  get "/drivers/dashboard" , controller: :drivers , action: :dash , as: :driver_dash
  get "/riders/dashboard" , controller: :riders , action: :dash , as: :rider_dash
  get "/rides/waiting" , controller: :rides , action: :waiting , as: :waiting
  get "/booking_requests/destroy" , controller: :booking_requests , action: :destroy , as: :booking_requests_destroy
  get "/drivers/available_ride" , controller: :drivers , action: :available_ride , as: :available_ride
  get "drivers/edit_standby_city" , controller: :drivers , action: :edit_standby_city , as: :edit_standby_city
  get "/drivers/city_change" , controller: :drivers , action: :city_change , as: :city_change
  get "/rides/riding" , controller: :rides , action: :riding , as: :riding
  get "/rides/finish_waiting" , controller: :rides , action: :finish_waiting , as: :finish_waiting
  get "/payments/waiting_payment" , controller: :payments , action: :waiting_payment , as: :waiting_payment
  get "/payments/successful" , controller: :payments , action: :successful , as: :successful
  post "/drivers/rating_change" , controller: :drivers , action: :rating_change , as: :rating_change
  get "/vehicles/change_primary_vehicle" , controller: :vehicles , action: :change_primary_vehicle , as: :change_primary_vehicle
  get "/vehicles/set_primary_vehicle" , controller: :vehicles , action: :set_primary_vehicle , as: :set_primary_vehicle
  get "/drivers/show" => "drivers#show"
  get "/drivers/edit" => "drivers#edit"
  patch "/drivers/update" => "drivers#update"
  get "/riders/show" => "riders#show"
  get "/homes/check" => "homes#check"

  resources :drivers
  resources :riders , only: [:show]
  resources :booking_requests , only: [:new , :create , :destroy]
  resources :locations , only: [:new , :create]
  resources :rides , only: [:index , :new , :create]
  resources :bills , only: [:new , :create]
  resources :payments , only: [:new , :create]
  resources :vehicles , only: [:new , :create , :destroy]

  #Exception Routes
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'

 
  

   # API routes
   namespace :api , default: {format: :json} do
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    # use_doorkeeper
   
    # devise_for :users
    
    devise_for :users , controllers:{
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }

    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
    # Defines the root path route ("/")
    # root "articles#index"
    
    root controller: :homes , action: :index , as: :home
    get "/drivers/dashboard" , controller: :drivers , action: :dash , as: :driver_dash
    get "/riders/dashboard" , controller: :riders , action: :dash , as: :rider_dash
    get "/rides/waiting" , controller: :rides , action: :waiting , as: :waiting
    get "/booking_requests/destroy" , controller: :booking_requests , action: :destroy , as: :booking_requests_destroy
    get "/drivers/available_ride" , controller: :drivers , action: :available_ride , as: :available_ride
    get "drivers/edit_standby_city" , controller: :drivers , action: :edit_standby_city , as: :edit_standby_city
    get "/drivers/city_change" , controller: :drivers , action: :city_change , as: :city_change
    get "/rides/riding" , controller: :rides , action: :riding , as: :riding
    get "/rides/finish_waiting" , controller: :rides , action: :finish_waiting , as: :finish_waiting
    get "/payments/waiting_payment" , controller: :payments , action: :waiting_payment , as: :waiting_payment
    get "/payments/successful" , controller: :payments , action: :successful , as: :successful
    post "/drivers/rating_change" , controller: :drivers , action: :rating_change , as: :rating_change
    get "/vehicles/change_primary_vehicle" , controller: :vehicles , action: :change_primary_vehicle , as: :change_primary_vehicle
    get "/vehicles/set_primary_vehicle" , controller: :vehicles , action: :set_primary_vehicle , as: :set_primary_vehicle

    #Custom API's
    get "/drivers/drivers_with_standby_city" , controller: :drivers , action: :drivers_with_standby_city , as: :drivers_with_standby_city
    get "/drivers/drivers_with_rating" , controller: :drivers , action: :drivers_with_rating , as: :drivers_with_rating
    get "/locations/get_all_default_locations" , controller: :locations , action: :get_all_default_locations , as: :get_all_default_locations
    get "/locations/get_all_rider_personal_locations" , controller: :locations , action: :get_all_rider_personal_locations , as: :get_all_rider_personal_locations
    get "/vehicles/get_vehicles_with_vehicle_type" , controller: :vehicles , action: :get_vehicles_with_vehicle_type , as: :get_vehicles_with_vehicle_type


    #own_index_routes
    get "/bills/your_bills" , controller: :bills , action: :your_bills 
    get "/booking_requests/your_booking_requests" , controller: :booking_requests , action: :your_booking_requests
    get "/payments/your_payments" , controller: :payments , action: :your_payments
    get "/rides/your_rides" , controller: :rides , action: :your_rides
    get "/vehicles/your_vehicles" , controller: :vehicles , action: :your_vehicles
    
  
    resources :drivers 
    resources :riders
    resources :booking_requests
    resources :locations
    resources :rides
    resources :bills
    resources :payments
    resources :vehicles
   

  end



  
  
end

app/controllers/api/homes_controller.rb
class Api::HomesController < Api::ApiController
    
    def index 
       
        msg = "Welcome To Kapido , India's Fastest Taxi Service"
        render json: { message: msg } , status: :ok
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
    def index 
        
    end

    def check
    end
end

app/views/home/_alert.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert" style="margin-right: 350px ; margin-left: 380px; font-size: 1.25em ; text-align: center">
  <%= alert %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/home/_error.html.erb
<%if model.errors.any? %>
<div class="alert alert-danger alert-dismissible fade show" role="alert" style="margin-left: 400px; margin-right: 400px">
    <div class="header" style="font-style: italic ; font-size: 1.5em">
      There were some errors with your submission
    </div>
      <br>
  <%model.errors.each do |error| %>
    <ul class="list">
      <li><%=error.full_message %></li>
    </ul>
    <%end %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<%end %>

app/views/home/_navbar.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">


    <p>&nbsp &nbsp &nbsp</p>

    

  <%if user_signed_in?%>
    <%if current_user.rider?%>
      <a class = "navbar-brand" href = "/riders/dashboard"><b>Kapido</b></a>
    <%else%>
      <a class = "navbar-brand" href = "/drivers/dashboard"><b>Kapido</b></a> 
    <%end%>

  <%else%>
    
    <a class="navbar-brand" href="/"><b>Kapido</b></a>
  <%end%>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
      <%if user_signed_in?%>
        <%if  current_user.driver?%>
          <%= link_to "Dashboard", driver_dash_path , class: "nav-link " %>
        <%else%>
          <%= link_to "Dashboard", rider_dash_path , class: "nav-link" %>
        <%end%>
      <%else%>
         <li> <%= link_to "Login",  new_user_session_path , class: "nav-link"%> </li>
        <li> <%= link_to "Signup", new_user_registration_path , class: "nav-link" %> </li>
      <%end%>
      </li>

      <li class = "nav-item active">
        <% if user_signed_in? %>
            <% if current_user.rider? %>
                <%= link_to "Book ride", new_booking_request_path , class: "nav-link" %>
            <% else %>
                <%= link_to "Available Rides", available_ride_path , class: "nav-link" %>
            <% end %>
        <% end %>
      </li>

      <%if user_signed_in? and current_user.driver?%>
         
        <li class = "nav-item active">
          <%= link_to "Change city", edit_standby_city_path , class: "nav-link"%>
        </li>
        <li class = "nav-item active">
          <%= link_to "Add Vehicle", new_vehicle_path , class: "nav-link" %>
        </li>
        <li class = "nav-item active">
          <%= link_to "Change Primary Vehicle", change_primary_vehicle_path , class: "nav-link" %>
        </li>
      <% end %>
    
    <% if user_signed_in? %>
      <% if current_user.driver? %>
        <li class = "nav-item active">
          <%= link_to "View Profile", driver_path(id: current_user.userable.id) , class: "nav-link" %>  
        </li>
      <% else %>
        <li class = "nav-item active">
        <%= link_to "View Profile", rider_path(id: current_user.userable.id) , class: "nav-link" %>  
        </li>
      <% end %>
    <% end %>

    <% if user_signed_in? && current_user.userable.current_ride_id %>
        <li class = "nav-item active">
        <%= link_to "Current Ride", riding_path(id: current_user.userable.current_ride_id ) , class: "nav-link" %>  
        </li>

    <% end %>
    

      <%if user_signed_in? && current_user.driver? %>

        <div style = "display:inline ; margin-left : 400px"> 
        <%= link_to "Signout", destroy_user_session_path ,data: { turbo_method: :delete , turbo_confirm: "Are you sure to sign out ? " }  , class: "nav-link"%>
        </div>


        <div style = "display:inline">

          <li class="nav-item">
          <a class="nav-link disabled">Your Ride , Your Right</a>
        </li>
        </div>

      <% elsif user_signed_in? && current_user.rider? %>

      <div style = "display:inline ; margin-left : 800px"> 
      <%= link_to "Signout", destroy_user_session_path ,data: { turbo_method: :delete , turbo_confirm: "Are you sure to sign out ? " }  , class: "nav-link"%>
      </div>


      <div style = "display:inline">

        <li class="nav-item">
        <a class="nav-link disabled">Your Ride , Your Right</a>
      </li>
      </div>

      <% else %>

      <div style = "display:inline ; margin-left: 1250px">

      <li class="nav-item">
      <a class="nav-link disabled">Your Ride , Your Right</a>
    </li>
    </div>
      

      <%end%>


      

     

      
     
    </ul>
    <%2
=begin%>
 <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form> 
<%
=end%>
  </div>
</nav>

app/views/home/_notice.html.erb
<div class="alert alert-success alert-dismissible fade show" role="alert" style="margin-right: 100px ; margin-left: 380px font-size: 1.25em ; text-align : center">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/home/_sidebar.html.erb
<div class="ui sidebar inverted vertical menu">
    <a class="item">
      1
    </a>
    <a class="item">
      2
    </a>
    <a class="item">
      3
    </a>
  </div>
  <div class="pusher">
    <!-- Site content !-->
  </div>