config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
 
  # devise_for :users
  
  devise_for :users , controllers:{
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root controller: :homes , action: :index , as: :home
  get "/drivers/dashboard" , controller: :drivers , action: :dash , as: :driver_dash
  get "/riders/dashboard" , controller: :riders , action: :dash , as: :rider_dash
  get "/rides/waiting" , controller: :rides , action: :waiting , as: :waiting
  get "/booking_requests/destroy" , controller: :booking_requests , action: :destroy , as: :booking_requests_destroy
  get "/drivers/available_ride" , controller: :drivers , action: :available_ride , as: :available_ride
  get "drivers/edit_standby_city" , controller: :drivers , action: :edit_standby_city , as: :edit_standby_city
  get "/drivers/city_change" , controller: :drivers , action: :city_change , as: :city_change
  get "/rides/riding" , controller: :rides , action: :riding , as: :riding
  get "/rides/finish_waiting" , controller: :rides , action: :finish_waiting , as: :finish_waiting
  get "/payments/waiting_payment" , controller: :payments , action: :waiting_payment , as: :waiting_payment
  get "/payments/successful" , controller: :payments , action: :successful , as: :successful
  post "/drivers/rating_change" , controller: :drivers , action: :rating_change , as: :rating_change
  get "/vehicles/change_primary_vehicle" , controller: :vehicles , action: :change_primary_vehicle , as: :change_primary_vehicle
  get "/vehicles/set_primary_vehicle" , controller: :vehicles , action: :set_primary_vehicle , as: :set_primary_vehicle
  get "/drivers/show" => "drivers#show"
  get "/drivers/edit" => "drivers#edit"
  patch "/drivers/update" => "drivers#update"
  get "/riders/show" => "riders#show"
  get "/homes/check" => "homes#check"

  resources :drivers
  resources :riders , only: [:show]
  resources :booking_requests , only: [:new , :create , :destroy]
  resources :locations , only: [:new , :create]
  resources :rides , only: [:index , :new , :create]
  resources :bills , only: [:new , :create]
  resources :payments , only: [:new , :create]
  resources :vehicles , only: [:new , :create , :destroy]

  #Exception Routes
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'

 
  

   # API routes
   namespace :api , default: {format: :json} do
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    # use_doorkeeper
   
    # devise_for :users
    
    devise_for :users , controllers:{
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }

    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
    # Defines the root path route ("/")
    # root "articles#index"
    
    root controller: :homes , action: :index , as: :home
    get "/drivers/dashboard" , controller: :drivers , action: :dash , as: :driver_dash
    get "/riders/dashboard" , controller: :riders , action: :dash , as: :rider_dash
    get "/rides/waiting" , controller: :rides , action: :waiting , as: :waiting
    get "/booking_requests/destroy" , controller: :booking_requests , action: :destroy , as: :booking_requests_destroy
    get "/drivers/available_ride" , controller: :drivers , action: :available_ride , as: :available_ride
    get "drivers/edit_standby_city" , controller: :drivers , action: :edit_standby_city , as: :edit_standby_city
    get "/drivers/city_change" , controller: :drivers , action: :city_change , as: :city_change
    get "/rides/riding" , controller: :rides , action: :riding , as: :riding
    get "/rides/finish_waiting" , controller: :rides , action: :finish_waiting , as: :finish_waiting
    get "/payments/waiting_payment" , controller: :payments , action: :waiting_payment , as: :waiting_payment
    get "/payments/successful" , controller: :payments , action: :successful , as: :successful
    post "/drivers/rating_change" , controller: :drivers , action: :rating_change , as: :rating_change
    get "/vehicles/change_primary_vehicle" , controller: :vehicles , action: :change_primary_vehicle , as: :change_primary_vehicle
    get "/vehicles/set_primary_vehicle" , controller: :vehicles , action: :set_primary_vehicle , as: :set_primary_vehicle

    #Custom API's
    get "/drivers/drivers_with_standby_city" , controller: :drivers , action: :drivers_with_standby_city , as: :drivers_with_standby_city
    get "/drivers/drivers_with_rating" , controller: :drivers , action: :drivers_with_rating , as: :drivers_with_rating
    get "/locations/get_all_default_locations" , controller: :locations , action: :get_all_default_locations , as: :get_all_default_locations
    get "/locations/get_all_rider_personal_locations" , controller: :locations , action: :get_all_rider_personal_locations , as: :get_all_rider_personal_locations
    get "/vehicles/get_vehicles_with_vehicle_type" , controller: :vehicles , action: :get_vehicles_with_vehicle_type , as: :get_vehicles_with_vehicle_type


    #own_index_routes
    get "/bills/your_bills" , controller: :bills , action: :your_bills 
    get "/booking_requests/your_booking_requests" , controller: :booking_requests , action: :your_booking_requests
    get "/payments/your_payments" , controller: :payments , action: :your_payments
    get "/rides/your_rides" , controller: :rides , action: :your_rides
    get "/vehicles/your_vehicles" , controller: :vehicles , action: :your_vehicles
    
  
    resources :drivers 
    resources :riders
    resources :booking_requests
    resources :locations
    resources :rides
    resources :bills
    resources :payments
    resources :vehicles
   

  end



  
  
end

app/models/driver.rb
class Driver < ApplicationRecord
   
    #Associations
    has_one_attached :liscense_image , dependent: :destroy
    has_one :user , as: :userable , dependent: :destroy
    
    has_and_belongs_to_many :vehicles , join_table: :drivers_vehicles
    has_many :payments
    has_many :riders , through: :payments
   has_many :rides

    #Validations    
    validates :liscense_no , :driver_rating , presence: true
    validates :driver_rating, numericality: { less_than_or_equal_to: 5 , greater_than_or_equal_to: 0}


    scope :rating_less_than_3 , -> { Driver.where("driver_rating < ?" , 3) }
    scope :rating_greater_than_3 , -> { Driver.where("driver_rating >= ?" , 3) }

end

app/controllers/api/drivers_controller.rb
class Api::DriversController < Api::ApiController
  
  # before_action :authenticate_user!
  before_action :is_driver? , except: [:index, :show , :drivers_with_standby_city , :drivers_with_rating_above_3]

  
  def index

    drivers = Driver.all
    if drivers.empty?
      render json: {message: "No drivers available"} , status: :no_content
    else
      render json: drivers , status: :ok
    end

  end


  def show

    driver = Driver.find(params[:id])
    if driver
      render json: driver , status: :ok
    else
      render json: {message: "No driver found with the id #{params[:id]}"} , status: :not_found
    end

  end

  
 

 

  def update
  
  if current_user.userable.update(standby_city: params[:city])
    render json: current_user.userable , status: :ok
  else
    render json: {error: current_user.userable.errors.full_messages } , status: :unprocessable_entity
  end
  
  end

  
  

  def available_ride
    
    primaryVehicle = Vehicle.find_by(id: current_user.userable.primary_vehicle_id)
    available = BookingRequest.where(city: params[:city] , booking_status: "available" , vehicle_type: primaryVehicle.vehicle_type)
    
    
    if available.size == 0
     
      render json: {  message: "No rides available" } , status: :no_content
    else
      
      render json: available , status: :ok
    end

  end



  #Custom Api Methods
  def drivers_with_standby_city
    
    drivers = Driver.where(standby_city: params[:city])
    
    if drivers.empty?
      render json: { messsage: "No drivers available in the city #{params[:city]}" } , status: :no_content
    else
      render json: drivers , status: :ok
    end
  end

  

  def drivers_with_rating


    if params[:rating].to_i < 0 || params[:rating].to_i > 5
      render json: { message: "The rating must be within the range of 0-5" } , status: :bad_request
      return 
    end


    driver = Driver.where("driver_rating >= ?", params[:rating].to_i)
    if driver.empty?
      render json: { message: "No drivers available with the given rating #{params[:rating].to_i}" } , status: :no_content
    else
      render json: driver , status: :ok
    end
  end


  private
  def is_driver?
    unless user_signed_in? && current_user.driver?
      render json: { message: "You are not authorized to view this page"} , status: :forbidden
    end
  end

end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  
  before_action :authenticate_user!
  before_action :is_driver? , except: [:rating_change]
  
  

  def show

    
    unless params[:id].to_i == current_user.userable.id
      flash[:alert] = "Unauthorized action"
      redirect_to driver_dash_path
      return 
    end

    @driver = Driver.find_by(id: params[:id])

  end

  

  
  def edit

    unless params[:id] == current_user.userable.id
      flash[:alert] = "Unauthorized action"
      redirect_to driver_dash_path
      return 
    end

    @cid = params[:id]
    
  end

  def update
    driver = Driver.find_by(id: current_user.userable.id)
    driver.standby_city = params[:driver][:standby_city]
    if driver.save
      flash[:notice] = "Your standing city changed successfully"
      redirect_to driver_dash_path
    else
      render :edit_standby_city
    end
  end

  

  def dash
    @rides = Ride.where(driver_id: current_user.userable.id)
    @payments = Payment.where(driver_id: current_user.userable.id)
    @earnings = 0
    @payments.each do |payment|
      if payment.amount
        @earnings = @earnings + payment.amount
      end
    end
    @rating = current_user.userable.driver_rating
    
    
  end

  def edit_standby_city
    @driver = Driver.find_by(id: current_user.userable.id)
  end
  
  def rating_change

    if current_user.driver?
      flash[:alert] = "Unauthorized action"
      redirect_to driver_dash_path
      return 
    end

    @paymentId = params[:driver][:id].to_i
    @payment = Payment.find_by(id: @paymentId)
    @driver = Driver.find_by(id: @payment.driver_id)
    @oldRating = @driver.driver_rating
    @newRating = (@oldRating + params[:driver][:driver_rating].to_i)/2
    @driver.update(driver_rating: @newRating)
    flash[:notice] = "Rating updated for the driver"
    redirect_to rider_dash_path
  end
  

  def available_ride
    @primaryVehicle = Vehicle.find_by(id: current_user.userable.primary_vehicle_id)
    @available = BookingRequest.where(city: current_user.userable.standby_city , booking_status: "available" , vehicle_type: @primaryVehicle.vehicle_type)
  end

  private
  def is_driver?
    
    unless user_signed_in? && current_user.driver? 
      flash[:alert] = "Unauthorized action"
      if user_signed_in?
        redirect_to rider_dash_path
      else
        redirect_to new_user_session_path
      end
    end
  end
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/views/drivers/available_ride.html.erb
<div style = "float:left;width:10px;height:10px;margin-left:30px">
  <img src = "<%=image_path('available_rides_1.jpg')%>" width=950px height=700px style = "position:fixed;">
</div> 

















<div style = "float:right ; margin-right : 220px">


<div style = "display : flex ; flex-direction : column">



<% if current_user.userable.riding_status == "on_ride"%>
    <div class="card shadow shadow-md" style="width: 30rem;">
  <div class="card-body">
    <h2 class = "display-6 lead" > YOU ARE ON RIDE </h2>
    <h2>  </h2>
    </div> </div>
<% else %>
<%unless @available.size == 0%>
    <h2 class = "display-6 lead" >THE RIDES FOR YOU </h2>
    <br><br>

    <%@available.each do |i|%>
        
            <div class="card bg-light mb-3 shadow shadow-md" style="max-width: 18rem;">
  <div class="card-header" style = "text-align:center"> <p class = "display-6 lead"> Ride <%=@available.find_index(i)+1%>  </p> </div>
  <div class="card-body">
    <h6 class="card-title"> <p class = "display-7 lead" > <%="From : #{i.from_location_name}"%> </p> </h6>
    <h6 class="card-title"> <p class = "display-7 lead" > <%="To : #{i.to_location_name}"%> </p> </h6>
    <% @rider = User.find_by(userable_id: i.rider_id) %>
    <h6 class = "card-title"> <p class = "display-7 lead" > <%="Rider Name : #{@rider.name}"%> </p> </h6>
     <h6 class = "card-title"> <p class = "display-7 lead" > <%= "Rider Age : #{@rider.age}" %> </p> </h6>
      <h6 class = "card-title"> <p class = "display-7 lead" > <%= "Rider Mobile : #{@rider.mobile_no}" %> </p> </h6>
    
    <%= link_to "Accept this ride", new_ride_path(id: i.id) , class: "btn btn-primary btn-sm" %>
  </div>
</div>
           
        
    <%end%>
</div>

<%else%>
 <div class="card shadow shadow-md" style="width: 30rem;">
  <div class="card-body">
  <h2 class = "display-6 lead" > NO RIDES </h2>
  <h4 class = "display-6 lead" > AVAILABLE RIGHT NOW !</h4>
  </div>
  </div>
<%end%>

<% end %>

</div>

app/views/drivers/dash.html.erb
<div style = "float:left;width:10px;height:10px;">
  <img src = "<%=image_path('driver-dash.jpg')%>" width=950px height=700px style = "position:fixed;">
</div> 







<div style = "float:right ; margin-right:220px ; margin-top: 150px">
<h1 class = "display-5 lead"> DRIVER DASHBOARD </h1>
<br>


<h3 class = "display-6 lead" >  View your analytics here  </h3>
<br>

<% unless current_user.userable.standby_city%>
    <h1> Enter your standby location </h1>
    <%= link_to "Set Standing Location", edit_standby_city_path , class: "btn btn-primary btn-sm"%>
    <br> <br>
<%end%>

<% unless current_user.userable.primary_vehicle_id %>
  <h1> Set your primary vehicle first </h1>
  <%= link_to "Set Primary Vehicle", change_primary_vehicle_path , class: "btn btn-primary btn-sm"%>
  <br><br>
<% end %>

<% unless current_user.userable.riding_status %>
    <% current_user.userable.update(riding_status: "off_ride") %>
  
<% end %>
<div style = "display : flex ; justify-content : space-around;">
    
    <div class="card bg-light mb-3 border-info shadow shadow-md" style="max-width: 10rem;">
  <div class="card-header"> <p class = "display-7 lead"> <b>Total Rides</b> </p> </div>
  <div class="card-body">
    <h5 class="card-title"><p class = "display-6 lead"> <b> <%= @rides.length %> </b> </p> </h5>
    <%
=begin%>
 <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> 
<%
=end%>
<%= link_to "View your rides", rides_path , class: "display-7 lead btn btn-primary btn-sm"%>
  </div>
  
</div>



<div class="card bg-light mb-3 border-info shadow shadow-md" style="max-width: 25rem;margin-left:30px">
  <div class="card-header"> <p class = "display-7 lead"> <b>Total Earnings</b> </p> </div>
  <div class="card-body">
    <h5 class="card-title"> <p class = "display-6 lead"><b> <%= @earnings %> </b> </p> </h5>
    <%
=begin%>
 <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> 
<%
=end%>
  </div>
</div>


<div class="card bg-light mb-3 border-info shadow shadow-md" style="max-width: 25rem; margin-left : 30px">
  <div class="card-header"><p class = "display-7 lead"><b>Driver Rating</b></p></div>
  <div class="card-body">
    <h5 class="card-title"><p class = "display-6 lead"><b><%= @rating.round(2) %></b></p></h5>
    <%
=begin%>
 <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p> 
<%
=end%>
  </div>
</div>




    
</div>

<br><br>
</div>

app/views/drivers/edit.html.erb
<h1>Drivers#edit</h1>

app/views/drivers/edit_standby_city.html.erb
<div style = "float:left;width:10px;height:10px;margin-left:300px">
  <img src = "<%=image_path('standing_city.jpg')%>"  height=600px style = "position:absolute;">
</div> 


















<div style = "float:right ; margin-right:300px ; margin-top: 200px">
<h1 class = "display-6 lead" >STANDING CITY</h1>

<fieldset>
<legend><b></b></legend>
<%= form_for @driver , action: :update do |f|%>

 <div class="card shadow shadow-md" style="width: 30rem;">
  <div class="card-body">

    <b><%=f.label :standby_city , "CITY : " , class: "h6 display-8 lead " %></b>
    <%=f.text_field :standby_city , class: "form-control" , required: true%>

    <br>

    <%=f.submit "Submit" , class: "btn btn-primary btn-sm"%>
    </div>
    </div>

</fieldset>
    
<%end%>
</div>

app/views/drivers/show.html.erb
<div style = "float:left;width:10px;height:10px;">
  <img src = "<%=image_path('driver_show.jpg')%>"  height=650px style = "position:fixed;">
</div> 








<div style = "float:right" >

   <fieldset> 
   <h1 class = "display-6 lead">  <b> BASIC DETAILS </b>  </h1>

    <br> 

    <div class="card shadow shadow-md border-info" style="width: 30rem;">
  <div class="card-body">

    <h6 class = "lead">  <b> NAME : </b> <%= current_user.name %></h6>
    <h6 class = "lead" > <b> EMAIL :  </b> <%= current_user.email %></h6>
    <h6 class = "lead"> <b> AGE : </b> <%= current_user.age %></h6>
    <h6 class = "lead" > <b> MOBILE NUMBER :  </b> <%= current_user.mobile_no %></h6>
    <h6 class = "lead"><b> ROLE: </b> <%= current_user.role %></h6>

    </div>
    </div>

    </fieldset>

    <br> <br>

    <h1 class = "display-6 lead"> <b> ADDRESS </b> </h1>
    <br>

    <div class="card shadow shadow-md border-info" style="width: 30rem;">
  <div class="card-body">

    <h6 class = "lead"><b> DOOR NO :   <%= current_user.door_no %></h6>
    <h6 class = "lead" ><b> STREET :  </b><%= current_user.street %> </h6>
    <h6 class = "lead"><b> CITY :   </b><%= current_user.city %></h6>
    <h6 class = "lead"><b> DISTRICT :   </b><%= current_user.district %></h6>
    <h6 class = "lead"><b> STATE :  </b><%= current_user.state %></h6>
    <h6 class = "lead"><b> PINCODE : </b><%= current_user.pincode %> </h6>

    </div>
    </div>
    </fieldset>
    <br> <br>

    <fieldset>
   <h1 class = "display-6 lead"> <b> PROOFS </b> </h1>
   <br>

   <div class="card shadow shadow-md border-info" style="width: 30rem;">
  <div class="card-body">
    
    <h6 class = "lead"> <b> LISCENSE NO : </b>  <%= @driver.liscense_no %></h6>
    <h6 class = "lead"> <b> LISCENSE IMAGE : </b>  </h6>

    </div> </div>
    <br>

    <% if @driver.liscense_image.attached? %>
        <div class = "container-sm">
        <%= image_tag @driver.liscense_image , style: 'height:500px;width:900px;' %>    
        </div>
    <% else %>
        <p class = "lead"> No liscense card image was attached with this profile </p>
        <img src = "<%=image_path('identification.png')%>" width=900px height = 500px height= style = "position:absolute;">
    <% end%>

    </fieldset>
    
</div>

app/views/drivers/update.html.erb
<h1>Drivers#update</h1>
<p>Find me in app/views/drivers/update.html.erb</p>