config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
 
  # devise_for :users
  
  devise_for :users , controllers:{
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root controller: :homes , action: :index , as: :home
  get "/drivers/dashboard" , controller: :drivers , action: :dash , as: :driver_dash
  get "/riders/dashboard" , controller: :riders , action: :dash , as: :rider_dash
  get "/rides/waiting" , controller: :rides , action: :waiting , as: :waiting
  get "/booking_requests/destroy" , controller: :booking_requests , action: :destroy , as: :booking_requests_destroy
  get "/drivers/available_ride" , controller: :drivers , action: :available_ride , as: :available_ride
  get "drivers/edit_standby_city" , controller: :drivers , action: :edit_standby_city , as: :edit_standby_city
  get "/drivers/city_change" , controller: :drivers , action: :city_change , as: :city_change
  get "/rides/riding" , controller: :rides , action: :riding , as: :riding
  get "/rides/finish_waiting" , controller: :rides , action: :finish_waiting , as: :finish_waiting
  get "/payments/waiting_payment" , controller: :payments , action: :waiting_payment , as: :waiting_payment
  get "/payments/successful" , controller: :payments , action: :successful , as: :successful
  post "/drivers/rating_change" , controller: :drivers , action: :rating_change , as: :rating_change
  get "/vehicles/change_primary_vehicle" , controller: :vehicles , action: :change_primary_vehicle , as: :change_primary_vehicle
  get "/vehicles/set_primary_vehicle" , controller: :vehicles , action: :set_primary_vehicle , as: :set_primary_vehicle
  get "/drivers/show" => "drivers#show"
  get "/drivers/edit" => "drivers#edit"
  patch "/drivers/update" => "drivers#update"
  get "/riders/show" => "riders#show"
  get "/homes/check" => "homes#check"

  resources :drivers
  resources :riders , only: [:show]
  resources :booking_requests , only: [:new , :create , :destroy]
  resources :locations , only: [:new , :create]
  resources :rides , only: [:index , :new , :create]
  resources :bills , only: [:new , :create]
  resources :payments , only: [:new , :create]
  resources :vehicles , only: [:new , :create , :destroy]

  #Exception Routes
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'

 
  

   # API routes
   namespace :api , default: {format: :json} do
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    # use_doorkeeper
   
    # devise_for :users
    
    devise_for :users , controllers:{
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }

    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
    # Defines the root path route ("/")
    # root "articles#index"
    
    root controller: :homes , action: :index , as: :home
    get "/drivers/dashboard" , controller: :drivers , action: :dash , as: :driver_dash
    get "/riders/dashboard" , controller: :riders , action: :dash , as: :rider_dash
    get "/rides/waiting" , controller: :rides , action: :waiting , as: :waiting
    get "/booking_requests/destroy" , controller: :booking_requests , action: :destroy , as: :booking_requests_destroy
    get "/drivers/available_ride" , controller: :drivers , action: :available_ride , as: :available_ride
    get "drivers/edit_standby_city" , controller: :drivers , action: :edit_standby_city , as: :edit_standby_city
    get "/drivers/city_change" , controller: :drivers , action: :city_change , as: :city_change
    get "/rides/riding" , controller: :rides , action: :riding , as: :riding
    get "/rides/finish_waiting" , controller: :rides , action: :finish_waiting , as: :finish_waiting
    get "/payments/waiting_payment" , controller: :payments , action: :waiting_payment , as: :waiting_payment
    get "/payments/successful" , controller: :payments , action: :successful , as: :successful
    post "/drivers/rating_change" , controller: :drivers , action: :rating_change , as: :rating_change
    get "/vehicles/change_primary_vehicle" , controller: :vehicles , action: :change_primary_vehicle , as: :change_primary_vehicle
    get "/vehicles/set_primary_vehicle" , controller: :vehicles , action: :set_primary_vehicle , as: :set_primary_vehicle

    #Custom API's
    get "/drivers/drivers_with_standby_city" , controller: :drivers , action: :drivers_with_standby_city , as: :drivers_with_standby_city
    get "/drivers/drivers_with_rating" , controller: :drivers , action: :drivers_with_rating , as: :drivers_with_rating
    get "/locations/get_all_default_locations" , controller: :locations , action: :get_all_default_locations , as: :get_all_default_locations
    get "/locations/get_all_rider_personal_locations" , controller: :locations , action: :get_all_rider_personal_locations , as: :get_all_rider_personal_locations
    get "/vehicles/get_vehicles_with_vehicle_type" , controller: :vehicles , action: :get_vehicles_with_vehicle_type , as: :get_vehicles_with_vehicle_type


    #own_index_routes
    get "/bills/your_bills" , controller: :bills , action: :your_bills 
    get "/booking_requests/your_booking_requests" , controller: :booking_requests , action: :your_booking_requests
    get "/payments/your_payments" , controller: :payments , action: :your_payments
    get "/rides/your_rides" , controller: :rides , action: :your_rides
    get "/vehicles/your_vehicles" , controller: :vehicles , action: :your_vehicles
    
  
    resources :drivers 
    resources :riders
    resources :booking_requests
    resources :locations
    resources :rides
    resources :bills
    resources :payments
    resources :vehicles
   

  end



  
  
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord

    #Associations
    has_and_belongs_to_many :drivers , join_table: :drivers_vehicles

    #Validations
    
    validates :vehicle_name , :vehicle_type , :no_of_seats ,  presence: true
end

app/controllers/api/vehicles_controller.rb
class Api::VehiclesController < Api::ApiController

  before_action :is_driver? , except: [:get_vehicles_with_vehicle_type , :index]

  def index
    vehicle = Vehicle.all
    if vehicle.empty?
      render json: { message: "No vehicle available" } , status: :no_content
    else
      render json: vehicle , status: :ok
    end
  end

  def show

    vehicle = Vehicle.find_by(id: params[:id].to_i)
    if vehicle
      if vehicle.driver_no == current_user.userable.id
        render json: vehicle , status: :ok
      else
        render json: { message: "You are not authorized to view this page" } , status: :forbidden
      end
    else
      render json: { message: "No vehicle found with the id #{params[:id]}" } , status: :not_found
    end

  end

  

  def create
    
    vehicle = Vehicle.new
    vehicle.vehicle_name = params[:name]
    vehicle.vehicle_type = params[:type]
    vehicle.no_of_seats = params[:seats]
    vehicle.driver_no = current_user.userable.id

    if vehicle.save
      render json: vehicle, status: :created
    else
      render json: {  error: vehicle.errors.full_messages } , status: :unprocessable_entity

    end

  end

  
  def update

    vehicle = Vehicle.find_by(id: params[:id].to_i)
    if vehicle
      if vehicle.driver_no == current_user.userable.id 
        vehicle.no_of_seats = params[:seats]
        if vehicle.save
          render json: vehicle, status: :accepted
        else
          render json: { error: vehicle.errors.full_messages } , status: :unprocessable_entity
        end
      else
        render json: { message: "You are not authorized to view this page"} , status: :forbidden
      end
    else
      render json: { message:  "No vehicle found with the id #{params[:id]}" } , status: :not_found
    end
  end



  def destroy

   
    vehicle = Vehicle.find_by(id: params[:id].to_i)
    if vehicle
      if vehicle.driver_no == current_user.userable.id 
        
        if vehicle.destroy
          render json: { message: "Vehicle destroyed successfully "}, status: :ok
        else
          render json: { error: vehicle.errors.full_messages } , status: :unprocessable_entity
        end
      else
        render json: { message: "You are not authorized to view this page"} , status: :forbidden
      end
    else
      render json: { message:  "No vehicle found with the id #{params[:id]}" } , status: :not_found
    end
    
  end


   #Custom API's
   def get_vehicles_with_vehicle_type 
    vehicles = Vehicle.where(vehicle_type: params[:vehicle_type])
    if vehicles.empty?
      render json: { message: "No vehicle available with the type #{params[:vehicle_type]}" } , status: :no_content
    else
      render json: vehicles , status: :ok
    end
   end
   
   def your_vehicles
    vehicles = Vehicle.where(driver_no: current_user.userable.id)
    if vehicles.empty?
      render json: { message: "No Vehicle found." } , status: :no_content
    else
      render json: vehicles , status: :ok
    end
   end

   private
   def is_driver?

    unless user_signed_in? && current_user.driver?
      render json: { message: "You are not authorized to view this page"} , status: :forbidden
      return 
    end

   end

  

end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController

  before_action :authenticate_user!  
  before_action :is_driver?
  

  def new
    @vehicle = Vehicle.new()
  end

  def create

    
    @vehicle = Vehicle.new(create_params)
    @vehicle.driver_no = current_user.userable.id 
 

    if @vehicle.save
      flash[:notice] = 'Your Vehicle added successfully'
      redirect_to driver_dash_path
    else
      render :new
    end
    

  end

  

  def destroy
  end

  def change_primary_vehicle
    @vehicles = Vehicle.where(driver_no: current_user.userable.id)
  end

  def set_primary_vehicle
    @vehicleId = params[:id].to_i
    @vehicles = Vehicle.where(driver_no: current_user.userable.id)
    @vehicles_id_array = @vehicles.pluck(:id)

    unless @vehicles_id_array.include?(@vehicleId)
      flash[:alert] = "Unauthorized action"
      redirect_to driver_dash_path
      return 
    end

    current_user.userable.update(primary_vehicle_id: @vehicleId)
    flash[:notice] = "Your Primary Vehicle updated successfully"
    redirect_to driver_dash_path
  end

  private
  def create_params
    params.require(:vehicle).permit(:vehicle_name , :vehicle_type , :no_of_seats , :vehicle_no)
  end

  private
  def is_driver?
    unless user_signed_in? && current_user.driver?
      flash[:alert] = "Unauthorized action"
      redirect_to rider_dash_path
    end
  end
  
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/vehicles/change_primary_vehicle.html.erb
<div style = "float:left;width:10px;height:10px;margin-left:30px">
  <img src = "<%=image_path('urban_racing_5.jpg')%>" width=950 height=650px style = "position:fixed;">
</div> 



<div style = "float:right ; margin-right : 300px">

<h1 class = "display-6 lead" > YOUR VEHICLES </h1>
<div style = "display : flex ; flex-direction : column">
<%unless @vehicles.size == 0%>
    
    <br><br>

    <%@vehicles.each do |i|%>
        
            <div class="card bg-light mb-3 shadow shadow-md" style="max-width: 25rem;">
  <div class="card-header" style = "text-align:center"> <p class = "display-7 lead" > <b> VEHICLE <%=@vehicles.find_index(i)+1%> </b> </p> </div>
  <div class="card-body">
    <h6 class="card-title"> <p class = "display-8 lead"> <b> <%="VEHICLE NAME:  #{i.vehicle_name}"%> </b> </p> </h6>
    <h6 class="card-title"> <p class = "display-8 lead"> <b> <%="VEHICLE TYPE:  #{i.vehicle_type}"%> </b> </h6>
    <h6 class="card-title"> <p class = "display-8 lead"> <b> <%="VEHICLE NUMBER:  #{i.vehicle_no}"%> </b> </h6>
  
    <% unless current_user.userable.primary_vehicle_id == i.id%>
    <%= link_to "Make as primary", set_primary_vehicle_path(id: i.id) , class: "btn btn-primary btn-sm" %>
    <% else %>
        <button type="button" class="btn btn-secondary btn-sm" disabled>Primary Vehicle</button>
    <% end %>
  </div>
</div>
            
        
    <%end%>
</div>

<%else%>
  <h1> Add your vehicle fist </h1>
  <%= link_to "Add Vehicle", new_vehicle_path %>
<%end%>

</div>

app/views/vehicles/new.html.erb
<div style = "float:left;width:10px;height:10px;margin-left:30px">
  <img src = "<%=image_path('urban_racing_8.jpg')%>" width=950 height=650px style = "position:absolute;">
</div> 









<div style = "float:right ; margin-right: 200px ; margin-top: 50px">


<fieldset>
<h6 class = "display-6 lead"> VEHICLE DETAILS </h6>
<br>

 <div class="card shadow shadow-md" style="width: 30rem;">
  <div class="card-body">
<%= form_for @vehicle , action: :create do |f|%>

    <%=f.label :vehicle_name , "VEHICLE NAME : " , class: "display-8 lead" %>
    <%=f.text_field :vehicle_name , class: "form-control form-control-sm" , required: true  %>

    <br>

    <%=f.label :vehicle_type , "VEHICLE TYPE : " , class: "display-8 lead" %>
    <br>
    <%vehicle_type_array = ["Bike" ,"Auto" ,  "Mini-Car" , "Sedan-Car" , "SUV-Car"]%>
    <%=f.select :vehicle_type , vehicle_type_array , class: "form-control display-9" , required: true%>
    <br>

    <br>

    <%=f.label :no_of_seats , "NO OF SEATS : " , class: "display-8 lead"%>
    <%=f.number_field :no_of_seats , class: "form-control" , required: true%>

    <br>

    <%=f.label :vehicle_no , "VEHICLE NUMBER : " , class: "display-8 lead"%>
    <%=f.text_field :vehicle_no , class: "form-control" , required: true%>

    <br>

    <%=f.submit "Submit" , class: "btn btn-primary btn-small"%>
    </div>
    </div>
</fieldset>
    
<%end%>
</div>