config/routes.rb
Rails.application.routes.draw do
  use_doorkeeper
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
 
  # devise_for :users
  
  devise_for :users , controllers:{
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root controller: :homes , action: :index , as: :home
  get "/drivers/dashboard" , controller: :drivers , action: :dash , as: :driver_dash
  get "/riders/dashboard" , controller: :riders , action: :dash , as: :rider_dash
  get "/rides/waiting" , controller: :rides , action: :waiting , as: :waiting
  get "/booking_requests/destroy" , controller: :booking_requests , action: :destroy , as: :booking_requests_destroy
  get "/drivers/available_ride" , controller: :drivers , action: :available_ride , as: :available_ride
  get "drivers/edit_standby_city" , controller: :drivers , action: :edit_standby_city , as: :edit_standby_city
  get "/drivers/city_change" , controller: :drivers , action: :city_change , as: :city_change
  get "/rides/riding" , controller: :rides , action: :riding , as: :riding
  get "/rides/finish_waiting" , controller: :rides , action: :finish_waiting , as: :finish_waiting
  get "/payments/waiting_payment" , controller: :payments , action: :waiting_payment , as: :waiting_payment
  get "/payments/successful" , controller: :payments , action: :successful , as: :successful
  post "/drivers/rating_change" , controller: :drivers , action: :rating_change , as: :rating_change
  get "/vehicles/change_primary_vehicle" , controller: :vehicles , action: :change_primary_vehicle , as: :change_primary_vehicle
  get "/vehicles/set_primary_vehicle" , controller: :vehicles , action: :set_primary_vehicle , as: :set_primary_vehicle
  get "/drivers/show" => "drivers#show"
  get "/drivers/edit" => "drivers#edit"
  patch "/drivers/update" => "drivers#update"
  get "/riders/show" => "riders#show"
  get "/homes/check" => "homes#check"

  resources :drivers
  resources :riders , only: [:show]
  resources :booking_requests , only: [:new , :create , :destroy]
  resources :locations , only: [:new , :create]
  resources :rides , only: [:index , :new , :create]
  resources :bills , only: [:new , :create]
  resources :payments , only: [:new , :create]
  resources :vehicles , only: [:new , :create , :destroy]

  #Exception Routes
  get '/404', to: 'errors#not_found'
  get '/500', to: 'errors#internal_server'
  get '/422', to: 'errors#unprocessable'

 
  

   # API routes
   namespace :api , default: {format: :json} do
    devise_for :admin_users, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)
    # use_doorkeeper
   
    # devise_for :users
    
    devise_for :users , controllers:{
      sessions: 'users/sessions',
      registrations: 'users/registrations'
    }

    # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
    # Defines the root path route ("/")
    # root "articles#index"
    
    root controller: :homes , action: :index , as: :home
    get "/drivers/dashboard" , controller: :drivers , action: :dash , as: :driver_dash
    get "/riders/dashboard" , controller: :riders , action: :dash , as: :rider_dash
    get "/rides/waiting" , controller: :rides , action: :waiting , as: :waiting
    get "/booking_requests/destroy" , controller: :booking_requests , action: :destroy , as: :booking_requests_destroy
    get "/drivers/available_ride" , controller: :drivers , action: :available_ride , as: :available_ride
    get "drivers/edit_standby_city" , controller: :drivers , action: :edit_standby_city , as: :edit_standby_city
    get "/drivers/city_change" , controller: :drivers , action: :city_change , as: :city_change
    get "/rides/riding" , controller: :rides , action: :riding , as: :riding
    get "/rides/finish_waiting" , controller: :rides , action: :finish_waiting , as: :finish_waiting
    get "/payments/waiting_payment" , controller: :payments , action: :waiting_payment , as: :waiting_payment
    get "/payments/successful" , controller: :payments , action: :successful , as: :successful
    post "/drivers/rating_change" , controller: :drivers , action: :rating_change , as: :rating_change
    get "/vehicles/change_primary_vehicle" , controller: :vehicles , action: :change_primary_vehicle , as: :change_primary_vehicle
    get "/vehicles/set_primary_vehicle" , controller: :vehicles , action: :set_primary_vehicle , as: :set_primary_vehicle

    #Custom API's
    get "/drivers/drivers_with_standby_city" , controller: :drivers , action: :drivers_with_standby_city , as: :drivers_with_standby_city
    get "/drivers/drivers_with_rating" , controller: :drivers , action: :drivers_with_rating , as: :drivers_with_rating
    get "/locations/get_all_default_locations" , controller: :locations , action: :get_all_default_locations , as: :get_all_default_locations
    get "/locations/get_all_rider_personal_locations" , controller: :locations , action: :get_all_rider_personal_locations , as: :get_all_rider_personal_locations
    get "/vehicles/get_vehicles_with_vehicle_type" , controller: :vehicles , action: :get_vehicles_with_vehicle_type , as: :get_vehicles_with_vehicle_type


    #own_index_routes
    get "/bills/your_bills" , controller: :bills , action: :your_bills 
    get "/booking_requests/your_booking_requests" , controller: :booking_requests , action: :your_booking_requests
    get "/payments/your_payments" , controller: :payments , action: :your_payments
    get "/rides/your_rides" , controller: :rides , action: :your_rides
    get "/vehicles/your_vehicles" , controller: :vehicles , action: :your_vehicles
    
  
    resources :drivers 
    resources :riders
    resources :booking_requests
    resources :locations
    resources :rides
    resources :bills
    resources :payments
    resources :vehicles
   

  end



  
  
end

app/models/ride.rb
class Ride < ApplicationRecord
    belongs_to :rider
    belongs_to :driver
    belongs_to :booking_request
    has_one :bill
    has_one :payment , through: :bill

    #Validations
    validates :ride_date , presence: true

    #callbacks
    before_create :set_ride_status
    before_create :set_booking_status_as_booked

    
    def set_ride_status
        self.ride_status = "on-ride"
    end

    
    def set_booking_status_as_booked
        # booking = BookingRequest.find_by(id: self.booking_request_id)
        # p booking
        # booking.booking_status = "booked"
        # booking.save
        # p booking
        self.booking_request.update(booking_status: "booked")
    end

end

app/controllers/api/rides_controller.rb
class Api::RidesController < Api::ApiController

  before_action :is_valid_user?

  
  def index
    rides = Ride.all
    if rides.empty?
      render json: { message: "Rides not found" } , status: :no_content
    else
      render json: rides , status: :ok
    end
  end



  def show
   
    ride = Ride.find_by(id: params[:id].to_i)
    if ride
      if ride.rider_id == current_user.userable.id || ride.driver_id == current_user.userable.id 
        render json: ride , status: :ok
      else
        render json: { message: 'You are not authorized to view this page' } , status: :forbidden
      end
    else
      render json: { message: "No ride found with the id #{params[:id].to_i}" } , status: :not_found
    end

  end

  
  def create
    

    if current_user.rider?
      render json: {  message: "You are not authorized to view this page"} , status: :forbidden
      return
    end

    ride = Ride.new()
    ride.rider_id = params[:rider_id]
    ride.driver_id = current_user.userable.id
    ride.booking_request_id = params[:booking_id]
    ride.ride_date = Date.today()

    if ride.save
      render json: ride , status: :accepted
    else
      render json: { error: ride.errors.full_messages } , status: :unprocessable_entity

    end
    

  end

 
  def update
    

    if current_user.rider?
      render json: { message: "You are not authorized to view this page"} , status: :forbidden
      return 
    end


    ride = Ride.find_by(id: params[:id].to_i)
    if ride
      if ride.driver_id == current_user.userable.id
        ride.ride_date = Date.today()
        if ride.save
          render json: ride , status: :ok
        else
          render json: { errors: ride.errors.full_messages } , status: :unprocessable_entity
        end
      else
        render json: { message: "You are not authorized to view this page "} , status: :forbidden
      end
    else
      render json: { message: "No ride available with the id #{params[:id].to_i}"} , status: :not_found
    end
  end


  def destroy
    
    if current_user.rider?
      render json: { message: "You are not authorized to view this page"} , status: :forbidden
      return 
    end


   

    ride = Ride.find_by(id: params[:id].to_i)
    if ride
      if ride.driver_id == current_user.userable.id
        if ride.destroy
          render json: { message: "Ride destroyed" } , status: :ok
        else
          render json: { errors: ride.errors.full_messages } , status: :unprocessable_entity
        end
      else
        render json: { message: "You are not authorized to view this page" } , status: :forbidden
      end
    else
      render json: { message: "No ride available with the id #{params[:id].to_i}"} , status: :not_found
    end


  end

  def your_rides
    if current_user.driver?
      rides = Ride.where(driver_id: current_user.userable.id)
      if rides.empty?
        render json: { message: "No rides available" } , status: :no_content
      else
        render json: rides , status: :ok
      end
    else
      rides = Ride.where(rider_id: current_user.userable.id)
      if rides.empty?
        render json: { message: "No rides available" } , status: :no_content
      else
        render json: rides , status: :ok
      end
    end
  end

  
  private
  def is_valid_user?
    unless user_signed_in?
      render json: { message: "You are not authorized to view this page" } , status: :forbidden
    end
  end
  

   
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController

  before_action :authenticate_user!

  
  def index
    @rides
    if current_user.driver?
      @rides = Ride.where(driver_id: current_user.userable.id)
    else
      @rides = Ride.where(rider_id: current_user.userable.id)
    end

    @rides = @rides.reverse()
  end

  

  def new
    # @booking = BookingRequest.find(params[:bid])
    # @ride = Ride.new
    # @ride.booking_request_id = params[:bid]
    # @ride.date = Date.now()
    # if current_user.role = 'Driver'
    #   @ride.driver_id = current_user.userable.id 
    # else 
    #   @ride.rider_id = current_user.userable.id
    # end
    # @ride.save
    if current_user.rider? 
      flash[:alert] = "Unauthorized action"
      redirect_to rider_dash_path
      return 
    end
    
    booking = BookingRequest.find_by(id: params[:id])
    current_user.userable.update(riding_status: "on_ride")

    
    @ride = Ride.new(booking_request_id: params[:id].to_i, driver_id: current_user.userable.id , rider_id: booking.rider_id , ride_date: Date.today())
    @ride.save
    booking.update(booking_status: 'booked')
    flash[:notice] = "You are on the ride" 
    current_user.userable.update(current_ride_id: @ride.id)  
    redirect_to riding_path(id: @ride.id)
  end

  def create
  end

  

  def waiting

    if current_user.driver?
      flash[:alert] = "Unauthorized action"
      redirect_to driver_dash_path
      return 
      
    end


    @bookingId = params[:id].to_i
    currentBooking = BookingRequest.find_by(id: @bookingId)

    unless current_user.userable.id == currentBooking.rider_id
      flash[:alert] = "Unauthorized action"
      redirect_to rider_dash_path
      return 
    end


    if currentBooking.booking_status == 'booked'
      flash[:notice] = "Your waiting was over"
      redirect_to finish_waiting_path(bid: currentBooking.id)
      return 
    end


  end

  def finish_waiting
    
    if current_user.driver?
      flash[:alert] = "Unauthorized action"
      redirect_to driver_dash_path
      return 
    end


    bid = params[:bid].to_i
    ride = Ride.find_by(booking_request_id: bid)
    
    if ride.save
      flash[:notice] = "You are moved to ride"
      current_user.userable.update(current_ride_id: ride.id)
      redirect_to riding_path(id: ride.id)
    else
      render :finish_waiting_path
    end

    
  end


  def riding
    @rideId = params[:id].to_i
    @ride = Ride.find_by(id: @rideId)
    @driver = User.find_by(userable_id: @ride.driver_id)
    @rider = User.find_by(userable_id: @ride.rider_id)
    if current_user.rider?
      bill = Bill.find_by(ride_id: @rideId)
      if bill
        flash[:notice] = "Ride ended successfully"
        redirect_to new_payment_path(rideId: @rideId)
      end
    end
  end

  

   
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/views/rides/index.html.erb
<div class="row">
<div style = "float:left;width:10px;height:10px;" class="col">
  <img src = "<%=image_path('rides.jpg')%>" width=700px height=500px style = "position:fixed;">
</div> 





<div class="col">
    
    <% if current_user.driver? %>
        <% unless @rides.empty?%>
        <legend class = "display-6 lead"><b><i>YOUR RIDES</i></b></legend>
        <br> <br>
        
        <div class = "rides_container" >
        <% @rides.each do |i| %>
             <div class="card bg-light border-success mb-3 shadow shadow-md" style="width: 18rem; height:18rem ; display: inline-block;">
             <br>
  <div class="card-title" style = "text-align:center"><p class = "display-7 lead"><b>RIDE <%=@rides.size - @rides.find_index(i)%></b></p></div>
  <div class="card-body">
    <% @booking = BookingRequest.find_by(id: i.booking_request_id) %>
    <% if @booking %>
    <h6 class="card-title"><p class = "lead"> <%="From : #{@booking.from_location_name}"%> </p> </h6>
    <h6 class="card-title"><p class = "lead">  <%="To : #{@booking.to_location_name}"%> </p> </h6>
    <% end %>
    <% @rider = User.find_by(userable_id: i.rider_id) %>
    <h6 class = "card-title"> <p class = "lead">  <%= "Rider Name : #{@rider.name}" %> </p> </h6>
    <h6 class = "card-title"><p class = "lead"> <%= "Ride date : #{i.ride_date}" %></p> </h6>
    <% @bill = Bill.find_by(ride_id: i.id) %>

    <% if @bill %>
    <h6 class = "card-title"> <p class = "lead" > <%= "Ride amount : #{@bill.bill_amount}" %> </p> </h6>
    <% end %>
    
  </div> 
      </div> &nbsp &nbsp &nbsp
            
        
    <%end%>
    </div>
    
    <% else %>
        <h1> No rides found </h1>
    <%end %>
        
    <% else %>



<% unless @rides.empty?%>
<legend class = "display-6 lead"><b><i>YOUR RIDES</i></b></legend>
<br> <br>

<div class = "rides_container" >
<% @rides.each do |i| %>
     <div class="card bg-light border-success mb-3 shadow shadow-md" style="width: 18rem; height:18rem ; display: inline-block;">
     <br>
<div class="card-title" style = "text-align:center"><p class = "display-7 lead"><b>RIDE <%=@rides.size - @rides.find_index(i)+1%></b></p></div>
<div class="card-body">
<% @booking = BookingRequest.find_by(id: i.booking_request_id) %>
<% if @booking %>
<h6 class="card-title"><p class = "lead"> <%="From : #{@booking.from_location_name}"%> </p> </h6>
<h6 class="card-title"><p class = "lead">  <%="To : #{@booking.to_location_name}"%> </p> </h6>
<% end %>
<% @driver = User.find_by(userable_id: i.driver_id) %>
<h6 class = "card-title"> <p class = "lead">  <%= "Rider Name : #{@driver.name}" %> </p> </h6>
<h6 class = "card-title"><p class = "lead"> <%= "Ride date : #{i.ride_date}" %></p> </h6>
<% @bill = Bill.find_by(ride_id: i.id) %>

<% if @bill %>
<h6 class = "card-title"> <p class = "lead" > <%= "Ride amount : #{@bill.bill_amount}" %> </p> </h6>
<% end %>

</div> 
</div> &nbsp &nbsp &nbsp
    

<%end%>
</div>


    <% else %>
        <h1> No rides found </h1>
    <%end %>

    <% end %>
</div>
</div>

app/views/rides/riding.html.erb
<div style = "float:left;width:10px;height:10px;margin-left:30px">
  <img src = "<%=image_path('riding.jpg')%>" width=950 height=650px style = "position:absolute;">
</div> 




<div style = "float:right ; margin-right:250px ; margin-top:80px">
<h1 class = "display-6 lead" > HOORAY !! </h1>
<h1 class = "display-6 lead"> YOU ARE ON RIDE NOW </h3>
<br> <br>

<% if current_user.driver?%>
    <!--Driver Riding Page-->

    <div class="card shadow shadow-md" style="width: 25rem;text-align:center;">
  <div class="card-body">
    <h5 class="card-title" style = "text-align:center"><p class = "display-7 lead"> <b> RIDER DETAILS </b> </p> </h5>
    <%
=begin%>
 <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6> 
<%
=end%>
    <p class="card-text display-8 lead"> <b> NAME : </b> <%= @rider.name%> </p>
    <p class="card-text display-8 lead"> <b> AGE : </b> <%= @rider.age%> </p>
    <p class="card-text display-8 lead"> <b> MOBILE NUMBER : </b> <%= @rider.mobile_no%> </p>
 

   
  </div>
</div>
  <br> <br>
   <p class="card-text display-8 lead"> <b> Reached the destintion ? </b></p>
    
     <%= link_to "End Ride", new_bill_path(rideId: @rideId)  , class: "btn btn-primary btn-sm" %>
    
   
    
<%else%>
    <!--Rider Riding Page-->


   <div class="card shadow shadow-md" style="width: 25rem;text-align:center;">
  <div class="card-body">
    <h5 class="card-title" style = "text-align:center"><p class = "display-7 lead"> <b>DRIVER DETAILS </b> </p> </h5>
    <%
=begin%>
 <h6 class="card-subtitle mb-2 text-muted">Card subtitle</h6> 
<%
=end%>
    <p class="card-text display-8 lead"> <b> NAME : </b> <%= @driver.name%> </p>
    <p class="card-text display-8 lead"> <b> AGE : </b> <%= @driver.age%> </p>
    <p class="card-text display-8 lead"> <b> MOBILE NUMBER : </b> <%= @driver.mobile_no%> </p>
 

   
  </div>
</div>


   
    
<%end%>
</div>

app/views/rides/waiting.html.erb
<div style = "float:left;width:10px;height:10px;margin-left:150px">
  <img src = "<%=image_path('waiting_ride.avif')%>"  height=700px style = "position:fixed;">
</div> 





<div style = "float:right ; margin-right:100px ; margin-top: 200px">


<div class="card shadow shadow-md" style="width: 40rem;">
  <div class="card-body">
<h1 class = "display-6 lead"> <b> Please wait... </b> </h1>
<p class = "display-7 lead"> In process of searching a Kapido captain for your ride !!</p>
 
 </div>
 </div>
 <br> <br>

<h6 class = "display-8 lead"> <b>Bored of getting waited</b> </h6>
<%= link_to "Cancel the ride",  booking_requests_destroy_path(bid: @bookingId) , data: {turbo_method: :delete , confirm: "Are you sure"} , class: "btn btn-primary btn-sm" %>
</div>